//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOEmprendimiento", Namespace="http://schemas.datacontract.org/2004/07/WcfEmprendimientos.DTOS")]
    [System.SerializableAttribute()]
    public partial class DTOEmprendimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NegocioWeb.ServiceReference1.DTOEvaluador[] EvaluadoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NegocioWeb.ServiceReference1.DTOPersona[] IntregrantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntajeFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TiempoPrevistoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NegocioWeb.ServiceReference1.DTOEvaluador[] Evaluadores {
            get {
                return this.EvaluadoresField;
            }
            set {
                if ((object.ReferenceEquals(this.EvaluadoresField, value) != true)) {
                    this.EvaluadoresField = value;
                    this.RaisePropertyChanged("Evaluadores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NegocioWeb.ServiceReference1.DTOPersona[] Intregrantes {
            get {
                return this.IntregrantesField;
            }
            set {
                if ((object.ReferenceEquals(this.IntregrantesField, value) != true)) {
                    this.IntregrantesField = value;
                    this.RaisePropertyChanged("Intregrantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuntajeFinal {
            get {
                return this.PuntajeFinalField;
            }
            set {
                if ((this.PuntajeFinalField.Equals(value) != true)) {
                    this.PuntajeFinalField = value;
                    this.RaisePropertyChanged("PuntajeFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TiempoPrevisto {
            get {
                return this.TiempoPrevistoField;
            }
            set {
                if ((this.TiempoPrevistoField.Equals(value) != true)) {
                    this.TiempoPrevistoField = value;
                    this.RaisePropertyChanged("TiempoPrevisto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOEvaluador", Namespace="http://schemas.datacontract.org/2004/07/WcfEmprendimientos.DTOS")]
    [System.SerializableAttribute()]
    public partial class DTOEvaluador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmprendimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JustificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEvaluadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmprendimiento {
            get {
                return this.IdEmprendimientoField;
            }
            set {
                if ((this.IdEmprendimientoField.Equals(value) != true)) {
                    this.IdEmprendimientoField = value;
                    this.RaisePropertyChanged("IdEmprendimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Justificacion {
            get {
                return this.JustificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.JustificacionField, value) != true)) {
                    this.JustificacionField = value;
                    this.RaisePropertyChanged("Justificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEvaluador {
            get {
                return this.NombreEvaluadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEvaluadorField, value) != true)) {
                    this.NombreEvaluadorField = value;
                    this.RaisePropertyChanged("NombreEvaluador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOPersona", Namespace="http://schemas.datacontract.org/2004/07/WcfEmprendimientos.DTOS")]
    [System.SerializableAttribute()]
    public partial class DTOPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEmprendimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEmprendimiento {
            get {
                return this.IdEmprendimientoField;
            }
            set {
                if ((this.IdEmprendimientoField.Equals(value) != true)) {
                    this.IdEmprendimientoField = value;
                    this.RaisePropertyChanged("IdEmprendimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEmprendimientos")]
    public interface IEmprendimientos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmprendimientos/ObtenerEmprendimientos", ReplyAction="http://tempuri.org/IEmprendimientos/ObtenerEmprendimientosResponse")]
        NegocioWeb.ServiceReference1.DTOEmprendimiento[] ObtenerEmprendimientos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmprendimientos/ObtenerEmprendimientos", ReplyAction="http://tempuri.org/IEmprendimientos/ObtenerEmprendimientosResponse")]
        System.Threading.Tasks.Task<NegocioWeb.ServiceReference1.DTOEmprendimiento[]> ObtenerEmprendimientosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmprendimientosChannel : NegocioWeb.ServiceReference1.IEmprendimientos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmprendimientosClient : System.ServiceModel.ClientBase<NegocioWeb.ServiceReference1.IEmprendimientos>, NegocioWeb.ServiceReference1.IEmprendimientos {
        
        public EmprendimientosClient() {
        }
        
        public EmprendimientosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmprendimientosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmprendimientosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmprendimientosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NegocioWeb.ServiceReference1.DTOEmprendimiento[] ObtenerEmprendimientos() {
            return base.Channel.ObtenerEmprendimientos();
        }
        
        public System.Threading.Tasks.Task<NegocioWeb.ServiceReference1.DTOEmprendimiento[]> ObtenerEmprendimientosAsync() {
            return base.Channel.ObtenerEmprendimientosAsync();
        }
    }
}
