//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegocioWeb.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOEmprendimiento", Namespace="http://schemas.datacontract.org/2004/07/WcfEmprendimientos.DTOS")]
    [System.SerializableAttribute()]
    public partial class DTOEmprendimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntajeFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TiempoPrevistoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuntajeFinal {
            get {
                return this.PuntajeFinalField;
            }
            set {
                if ((this.PuntajeFinalField.Equals(value) != true)) {
                    this.PuntajeFinalField = value;
                    this.RaisePropertyChanged("PuntajeFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TiempoPrevisto {
            get {
                return this.TiempoPrevistoField;
            }
            set {
                if ((this.TiempoPrevistoField.Equals(value) != true)) {
                    this.TiempoPrevistoField = value;
                    this.RaisePropertyChanged("TiempoPrevisto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IEmprendimientos")]
    public interface IEmprendimientos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmprendimientos/ObtenerEmprendimientos", ReplyAction="http://tempuri.org/IEmprendimientos/ObtenerEmprendimientosResponse")]
        NegocioWeb.ServiceReference1.DTOEmprendimiento[] ObtenerEmprendimientos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmprendimientos/ObtenerEmprendimientos", ReplyAction="http://tempuri.org/IEmprendimientos/ObtenerEmprendimientosResponse")]
        System.Threading.Tasks.Task<NegocioWeb.ServiceReference1.DTOEmprendimiento[]> ObtenerEmprendimientosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmprendimientosChannel : NegocioWeb.ServiceReference1.IEmprendimientos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmprendimientosClient : System.ServiceModel.ClientBase<NegocioWeb.ServiceReference1.IEmprendimientos>, NegocioWeb.ServiceReference1.IEmprendimientos {
        
        public EmprendimientosClient() {
        }
        
        public EmprendimientosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmprendimientosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmprendimientosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmprendimientosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NegocioWeb.ServiceReference1.DTOEmprendimiento[] ObtenerEmprendimientos() {
            return base.Channel.ObtenerEmprendimientos();
        }
        
        public System.Threading.Tasks.Task<NegocioWeb.ServiceReference1.DTOEmprendimiento[]> ObtenerEmprendimientosAsync() {
            return base.Channel.ObtenerEmprendimientosAsync();
        }
    }
}
